AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Local EKS-like Kubernetes cluster created with Floci and CloudFormation.

Parameters:
  ClusterName:
    Type: String
    Default: floci-eks-lab

  KubernetesVersion:
    Type: String
    Default: "1.29"

Resources:
  LabVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      Tags:
        - Key: Name
          Value: floci-eks-lab-vpc

  LabSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LabVpc
      CidrBlock: 10.10.1.0/24
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: floci-eks-lab-subnet-a

  LabSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LabVpc
      CidrBlock: 10.10.2.0/24
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: floci-eks-lab-subnet-b

  EksControlPlaneRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: floci-eks-lab-control-plane-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: floci-eks-lab-control-plane-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "*"
                Resource:
                  - "*"

  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt EksControlPlaneRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref LabSubnetA
          - !Ref LabSubnetB
      Tags:
        - Key: Project
          Value: learn-floci-eks-lab
        - Key: ManagedBy
          Value: cloudformation

Outputs:
  ClusterName:
    Description: EKS-like cluster name
    Value: !Ref EksCluster

  ClusterArn:
    Description: EKS-like cluster ARN
    Value: !GetAtt EksCluster.Arn

  VpcId:
    Description: Local VPC ID
    Value: !Ref LabVpc

  SubnetA:
    Description: Local subnet A
    Value: !Ref LabSubnetA

  SubnetB:
    Description: Local subnet B
    Value: !Ref LabSubnetB